[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/*"]

[programs.localnet]
antegen_thread_program = "AgV3xRAdyTe1wW4gTW2oAnzHiAGofsxC7jBVGGkzUQbY"

[programs.devnet]
antegen_thread_program = "AgV3xRAdyTe1wW4gTW2oAnzHiAGofsxC7jBVGGkzUQbY"

[programs.testnet]
antegen_thread_program = "AgV3xRAdyTe1wW4gTW2oAnzHiAGofsxC7jBVGGkzUQbY"

[programs.mainnet]
antegen_thread_program = "AgV3xRAdyTe1wW4gTW2oAnzHiAGofsxC7jBVGGkzUQbY"

[registry]
url = "https://api.apr.dev"

[toolchain]
anchor_version = "1.0.0-rc.1"
solana_version = "3.0.0"      # Solana version to use(applies to all Solana tools)
package_manager = "pnpm"
